Updated Purge feature:
myrteametrics/myrtea-engine-api pull request #124
Opened 2023-10-02 06:04 UTC by Ismail731404

- Improved Purge configuration settings.
- All necessary dependencies are now accounted for.
- Tables affected by the purge include:
  - situation_fact_history_v5
  - fact_history_v5
  - issue_detection_feedback_v3
  - issue_resolution_draft_v1
  - issue_resolution_v1
  - issues_v1
  - situation_history_v5

2023-10-02 09:09 UTC, htrmind7 requested changes
enrichir les logs lors du traitement de la purge pour avoir une meilleure visibilité : 
idéalement, il faudrait avoir : 
le count des lignes avant la purge
le count des lignes après la purge
la durée de la requête DELETE

question annexe : comment est gérer la récupération d'espace disque après la purge (la fameuse VACUUM FULL) ne devrait-on pas la lancer ?

2023-10-04 10:12 UTC, SchawnnDev requested changes
logs in english please

2023-10-05 14:12 UTC, SchawnnDev approved these changes

2023-10-05 14:27 UTC, htrmind7 approved these changes

2023-10-05 14:30 UTC, merged