récupérer les alertes de même key que l'alerte en cours
myrteametrics/myrtea-engine-api pull request #32
Opened 2022-07-08 13:43 UTC by NozitheloNcube

2022-07-26 12:18 UTC, cedricablain requested changes

2022-07-26 12:18 UTC, cedricablain commented on internals/explainer/issues/postgres_repository.go
> +
Supprimer saut de ligne

2022-07-26 12:18 UTC, cedricablain commented on internals/explainer/issues/postgres_repository.go
> +	}
La key est obligatoire ici (la méthode GetByKey attend forcement une key)
Tu peux donc le mettre directement dans la query + params. (pas de IF spécifique pour ce champ)

2022-07-26 12:18 UTC, cedricablain commented on internals/explainer/issues/postgres_repository.go
> +	}
La key est obligatoire ici (la méthode GetByKey attend forcement une key)
Tu peux donc le mettre directement dans la query + params. (pas de IF spécifique pour ce champ)

2022-07-26 12:18 UTC, cedricablain commented on internals/explainer/issues/repository.go
> +	GetByKey(key string, options models.SearchOptions, groups []int64) ([]models.Issue, int, error)
```suggestion
	GetByKeyByPage(key string, options models.SearchOptions, groups []int64) ([]models.Issue, int, error)
```

2022-07-26 12:18 UTC, cedricablain commented on internals/explainer/issues/postgres_repository.go
> +func (r *PostgresRepository) CountByKeyByPage(issuesKey string, groups []int64) (int, error) {
```suggestion
func (r *PostgresRepository) CountByKeyByPage(key string, groups []int64) (int, error) {
```

2022-07-26 12:18 UTC, cedricablain commented on internals/explainer/issues/postgres_repository.go
> +		params["issuesKey"] = issuesKey
```suggestion
		query += ` and i.key = :key`
		params["key"] = key
```

2022-07-26 12:18 UTC, cedricablain commented on internals/explainer/issues/postgres_repository.go
> +func (r *PostgresRepository) GetByKey(key string, options models.SearchOptions, groups []int64) ([]models.Issue, int, error) {
```suggestion
func (r *PostgresRepository) GetByKeyByPage(key string, options models.SearchOptions, groups []int64) ([]models.Issue, int, error) {
```

2022-07-26 12:18 UTC, cedricablain commented on internals/handlers/issues_handlers.go
> +
Supprimer saut de ligne

2022-07-26 12:18 UTC, cedricablain commented on internals/handlers/issues_handlers.go
> +	}
Déplacer ce bloc après la lecture de l'ensemble des paramètres de l'URL
(On lit d'abord tous les paramètres, et ensuite on interroge la base)

2022-07-26 12:18 UTC, cedricablain commented on internals/handlers/issues_handlers.go
> +
Supprimer saut de ligne

2022-07-27 10:10 UTC, NozitheloNcube commented on internals/explainer/issues/postgres_repository.go
> +
Quand je supprime la ligne et je sauvegarde, ça fait un saut de ligne

2022-07-28 12:41 UTC, cedricablain requested changes

2022-07-28 12:41 UTC, cedricablain commented on internals/explainer/issues/postgres_repository.go
> +	}
Supprimer l'option sur la key. Comme pour GetByKeyByPage, la key est obligatoire (et peut être inclus directement dans la query)

2022-07-28 13:17 UTC, cedricablain approved these changes

2022-07-28 13:18 UTC, merged