66 fix elasticsearch search pagination
myrteametrics/myrtea-engine-api pull request #83
Opened 2023-04-17 08:56 UTC by SchawnnDev

2023-04-17 10:25 UTC, cedricablain requested changes

2023-04-17 10:25 UTC, cedricablain commented on config/engine-api.toml
Pas de modification sur ce fichier

2023-04-17 10:25 UTC, cedricablain commented on internals/export/elasticsearchv8.go
> +		}
Pas besoin du code des baselines dans l'export des hits

2023-04-17 10:25 UTC, cedricablain commented on internals/export/elasticsearchv8.go
> +		}
A reporter plus haut (avant le `reader.ParseV8(...)`)
+
Se baser directement sur `response.Hits.Hits` ?

2023-04-17 10:25 UTC, cedricablain commented on internals/export/elasticsearchv8.go
> +		return nil, err // TODO: log soft err
Log-only error (but doesn't return)

2023-04-17 10:25 UTC, cedricablain commented on internals/handlers/export_handlers.go
> +func ExportFact(w http.ResponseWriter, r *http.Request) {
Eventuellement prévoir un paramètre en entrée pour que l'appelant "spécifie" le nom du fichier ? (approche plus générique)

2023-04-17 10:25 UTC, cedricablain commented on internals/handlers/export_handlers.go
> +}
Voir les utilitaires du fichier `internals/handlers/utils.go`
Potentiel ajout de nouvelles méthodes 

```go
func QueryParamToOptionnalString(r *http.Request, name string, orDefault string) (string, error) {}
func QueryParamToOptionnalStrings(r *http.Request, name string, orDefault []string) ([]string, error) {} 
```

2023-04-17 10:25 UTC, cedricablain commented on internals/router/routes.go
> +	r.Get("/export/facts/{id}", handlers.ExportFact)
Convention de nommage à discuter ?
```suggestion
	r.Get("/facts/{id}/export", handlers.ExportFact)
```

2023-04-17 10:54 UTC, SchawnnDev commented on internals/handlers/export_handlers.go
> +func ExportFact(w http.ResponseWriter, r *http.Request) {
Ok et si le paramètre n'est pas donné on met celui là par défaut

2023-04-17 10:55 UTC, SchawnnDev commented on internals/router/routes.go
> +	r.Get("/export/facts/{id}", handlers.ExportFact)
c'est vrai je préfère ça aussi

2023-04-17 11:07 UTC, SchawnnDev commented on internals/export/elasticsearchv8.go
> +		}
n'est pas a reporter plus haut car il faut que les données soient traitées et ajoutées au résultat final,
c'est juste pour éviter une nouvelle requête search car hits < 10000

2023-04-21 07:37 UTC, cedricablain approved these changes

2023-04-21 07:39 UTC, merged